import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer';
import type { SettlementEntry } from '@/types';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a1a' },
  header: { marginBottom: 24 },
  title: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: '#4338ca' },
  subtitle: { fontSize: 11, color: '#6b7280', marginTop: 4 },
  totalBadge: {
    marginTop: 10, backgroundColor: '#eef2ff', borderRadius: 6,
    padding: '8 12', alignSelf: 'flex-start',
  },
  totalText: { fontSize: 13, fontFamily: 'Helvetica-Bold', color: '#4338ca' },
  sectionTitle: {
    fontSize: 12, fontFamily: 'Helvetica-Bold', color: '#111827',
    marginTop: 20, marginBottom: 8, borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb', paddingBottom: 4,
  },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f9fafb', padding: '6 8', borderRadius: 4 },
  tableRow: { flexDirection: 'row', padding: '5 8', borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  colTitle: { flex: 3 },
  colAmount: { flex: 1.2, textAlign: 'right' },
  colPaidBy: { flex: 1.8 },
  headerText: { fontFamily: 'Helvetica-Bold', fontSize: 9, color: '#6b7280' },
  cellText: { fontSize: 9, color: '#374151' },
  settlementRow: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    backgroundColor: '#fffbeb', borderRadius: 6, padding: '7 10', marginBottom: 5,
    borderWidth: 1, borderColor: '#fde68a',
  },
  fromText: { fontSize: 10, color: '#dc2626', fontFamily: 'Helvetica-Bold' },
  toText: { fontSize: 10, color: '#059669', fontFamily: 'Helvetica-Bold' },
  amountText: { fontSize: 10, fontFamily: 'Helvetica-Bold', color: '#1a1a1a' },
  footer: { position: 'absolute', bottom: 24, left: 40, right: 40, textAlign: 'center', color: '#9ca3af', fontSize: 8 },
});

interface SheetPdfProps {
  title: string;
  total: number;
  transactions: Array<{ title: string; amount: number; paidBy: { name: string } }>;
  settlements: SettlementEntry[];
  generatedAt: string;
}

function SheetDocument({ title, total, transactions, settlements, generatedAt }: SheetPdfProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.subtitle}>Generated by SplitEase · {generatedAt}</Text>
          <View style={styles.totalBadge}>
            <Text style={styles.totalText}>Total Expenses: ${total.toFixed(2)}</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Transactions ({transactions.length})</Text>
        <View style={styles.tableHeader}>
          <Text style={[styles.headerText, styles.colTitle]}>TITLE</Text>
          <Text style={[styles.headerText, styles.colAmount]}>AMOUNT</Text>
          <Text style={[styles.headerText, styles.colPaidBy]}>PAID BY</Text>
        </View>
        {transactions.map((t, i) => (
          <View key={i} style={styles.tableRow}>
            <Text style={[styles.cellText, styles.colTitle]}>{t.title}</Text>
            <Text style={[styles.cellText, styles.colAmount]}>${t.amount.toFixed(2)}</Text>
            <Text style={[styles.cellText, styles.colPaidBy]}>{t.paidBy.name}</Text>
          </View>
        ))}

        <Text style={styles.sectionTitle}>
          {settlements.length === 0 ? 'Settlements — All Settled Up ✓' : `Settlements (${settlements.length} transfer${settlements.length > 1 ? 's' : ''})`}
        </Text>
        {settlements.map((s, i) => (
          <View key={i} style={styles.settlementRow}>
            <Text style={styles.fromText}>{s.from}</Text>
            <Text style={{ fontSize: 9, color: '#9ca3af' }}>pays</Text>
            <Text style={styles.toText}>{s.to}</Text>
            <Text style={styles.amountText}>${s.amount.toFixed(2)}</Text>
          </View>
        ))}

        <Text style={styles.footer}>SplitEase · splitease.app</Text>
      </Page>
    </Document>
  );
}

export async function generateSheetPdf(props: SheetPdfProps): Promise<Buffer> {
  const buffer = await renderToBuffer(<SheetDocument {...props} />);
  return Buffer.from(buffer);
}
