import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer';
import type { SettlementEntry } from '@/types';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a1a' },
  header: { marginBottom: 24 },
  title: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: '#4338ca' },
  subtitle: { fontSize: 11, color: '#6b7280', marginTop: 4 },
  totalBadge: {
    marginTop: 10, backgroundColor: '#eef2ff', borderRadius: 6,
    padding: '8 12', alignSelf: 'flex-start',
  },
  totalText: { fontSize: 13, fontFamily: 'Helvetica-Bold', color: '#4338ca' },
  sectionTitle: {
    fontSize: 12, fontFamily: 'Helvetica-Bold', color: '#111827',
    marginTop: 20, marginBottom: 8, borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb', paddingBottom: 4,
  },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f9fafb', padding: '6 8', borderRadius: 4 },
  tableRow: { flexDirection: 'row', padding: '5 8', borderBottomWidth: 1, borderBottomColor: '#f3f4f6', alignItems: 'flex-start' },
  colExpense: { flex: 2.2 },
  colPaidBy: { flex: 1.4 },
  colAmount:  { flex: 0.9, textAlign: 'right' },
  colShared:  { flex: 3, paddingLeft: 8 },
  headerText: { fontFamily: 'Helvetica-Bold', fontSize: 9, color: '#6b7280' },
  cellText:   { fontSize: 9, color: '#374151' },
  sharedEqual: { fontSize: 8, color: '#4338ca' },
  sharedSplit: { fontSize: 8, color: '#374151' },
  summaryRow: { flexDirection: 'row', padding: '5 8', borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  colSummaryName:   { flex: 2.5 },
  colSummaryAmount: { flex: 1.2, textAlign: 'right' },
  netPositive: { fontSize: 9, color: '#059669', fontFamily: 'Helvetica-Bold' },
  netNegative: { fontSize: 9, color: '#dc2626', fontFamily: 'Helvetica-Bold' },
  netZero:     { fontSize: 9, color: '#6b7280' },
  settlementRow: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    backgroundColor: '#fffbeb', borderRadius: 6, padding: '7 10', marginBottom: 5,
    borderWidth: 1, borderColor: '#fde68a',
  },
  fromText:   { fontSize: 10, color: '#dc2626', fontFamily: 'Helvetica-Bold' },
  toText:     { fontSize: 10, color: '#059669', fontFamily: 'Helvetica-Bold' },
  amountText: { fontSize: 10, fontFamily: 'Helvetica-Bold', color: '#1a1a1a' },
  footer: { position: 'absolute', bottom: 24, left: 40, right: 40, textAlign: 'center', color: '#9ca3af', fontSize: 8 },
});

interface Split {
  amount: number;
  participant: { name: string };
}

interface PdfTransaction {
  title: string;
  amount: number;
  paidBy: { name: string };
  splits: Split[];
}

export interface SheetPdfProps {
  title: string;
  total: number;
  transactions: PdfTransaction[];
  settlements: SettlementEntry[];
  generatedAt: string;
}

function sharedLabel(splits: Split[], total: number): { equal: boolean; label: string } {
  if (!splits || splits.length === 0) return { equal: false, label: '—' };

  const n = splits.length;
  const expectedEach = total / n;
  const isEqual = splits.every((s) => Math.abs(s.amount - expectedEach) < 0.02);

  if (isEqual) {
    const names = splits.map((s) => s.participant.name).join(', ');
    return { equal: true, label: `Equal among ${n}: ${names}` };
  }

  const parts = splits.map((s) => `${s.participant.name} $${s.amount.toFixed(2)}`).join(' · ');
  return { equal: false, label: parts };
}

function buildPersonSummary(transactions: PdfTransaction[]) {
  const paid = new Map<string, number>();
  const owed = new Map<string, number>();

  for (const tx of transactions) {
    const payer = tx.paidBy.name;
    paid.set(payer, (paid.get(payer) ?? 0) + tx.amount);
    for (const s of tx.splits) {
      const name = s.participant.name;
      owed.set(name, (owed.get(name) ?? 0) + s.amount);
    }
  }

  const names = Array.from(new Set([...paid.keys(), ...owed.keys()])).sort();
  return names.map((name) => {
    const p = paid.get(name) ?? 0;
    const o = owed.get(name) ?? 0;
    return { name, paid: p, owed: o, net: Math.round((p - o) * 100) / 100 };
  });
}

function SheetDocument({ title, total, transactions, settlements, generatedAt }: SheetPdfProps) {
  const personSummary = buildPersonSummary(transactions);
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.subtitle}>Generated by SplitEase · {generatedAt}</Text>
          <View style={styles.totalBadge}>
            <Text style={styles.totalText}>Total Expenses: ${total.toFixed(2)}</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Transactions ({transactions.length})</Text>

        <View style={styles.tableHeader}>
          <Text style={[styles.headerText, styles.colExpense]}>EXPENSE</Text>
          <Text style={[styles.headerText, styles.colPaidBy]}>PAID BY</Text>
          <Text style={[styles.headerText, styles.colAmount]}>AMOUNT</Text>
          <Text style={[styles.headerText, styles.colShared]}>SHARED WITH</Text>
        </View>

        {transactions.map((t, i) => {
          const { equal, label } = sharedLabel(t.splits, t.amount);
          return (
            <View key={i} style={styles.tableRow}>
              <Text style={[styles.cellText, styles.colExpense]}>{t.title}</Text>
              <Text style={[styles.cellText, styles.colPaidBy]}>{t.paidBy.name}</Text>
              <Text style={[styles.cellText, styles.colAmount]}>${t.amount.toFixed(2)}</Text>
              <Text style={[equal ? styles.sharedEqual : styles.sharedSplit, styles.colShared]}>
                {label}
              </Text>
            </View>
          );
        })}

        <Text style={styles.sectionTitle}>Summary by Person</Text>
        <View style={styles.tableHeader}>
          <Text style={[styles.headerText, styles.colSummaryName]}>PERSON</Text>
          <Text style={[styles.headerText, styles.colSummaryAmount]}>TOTAL PAID</Text>
          <Text style={[styles.headerText, styles.colSummaryAmount]}>TOTAL OWED</Text>
          <Text style={[styles.headerText, styles.colSummaryAmount]}>NET</Text>
        </View>
        {personSummary.map((row, i) => (
          <View key={i} style={styles.summaryRow}>
            <Text style={[styles.cellText, styles.colSummaryName, { fontFamily: 'Helvetica-Bold' }]}>
              {row.name}
            </Text>
            <Text style={[styles.cellText, styles.colSummaryAmount]}>${row.paid.toFixed(2)}</Text>
            <Text style={[styles.cellText, styles.colSummaryAmount]}>${row.owed.toFixed(2)}</Text>
            <Text style={[
              row.net > 0.005 ? styles.netPositive : row.net < -0.005 ? styles.netNegative : styles.netZero,
              styles.colSummaryAmount,
            ]}>
              {row.net > 0.005 ? '+' : ''}{row.net.toFixed(2)}
            </Text>
          </View>
        ))}

        <Text style={styles.sectionTitle}>
          {settlements.length === 0
            ? 'Settlements — All Settled Up ✓'
            : `Settlements (${settlements.length} transfer${settlements.length > 1 ? 's' : ''})`}
        </Text>
        {settlements.map((s, i) => (
          <View key={i} style={styles.settlementRow}>
            <Text style={styles.fromText}>{s.from}</Text>
            <Text style={{ fontSize: 9, color: '#9ca3af' }}>pays</Text>
            <Text style={styles.toText}>{s.to}</Text>
            <Text style={styles.amountText}>${s.amount.toFixed(2)}</Text>
          </View>
        ))}

        <Text style={styles.footer}>SplitEase · splitease.app</Text>
      </Page>
    </Document>
  );
}

export async function generateSheetPdf(props: SheetPdfProps): Promise<Buffer> {
  const buffer = await renderToBuffer(<SheetDocument {...props} />);
  return Buffer.from(buffer);
}
